.\" Copyright (C) 2005 Camilla Berglund
.\" Please see the file `COPYING' for license details.
.\"
.Dd November 21, 2005
.Os
.Dt DUFF 1
.Sh NAME
.Nm duff
.Nd duplicate file finder
.Sh SYNOPSIS
.Nm
.Op Fl LPaeqrt
.Op Fl f Ar format
.Op Fl l Ar limit
.Ar
.Nm
.Op Fl h
.Nm
.Op Fl v
.Sh DESCRIPTION
The
.Nm
utility reports any clusters of duplicates in the specified files and/or directories.
For each cluster of duplicate files,
.Nm
prints a customizable header on one line,
and then the names of all the files in the cluster, each on one line.
.Pp
The following options are available:
.Bl -tag -offset indent
.It Fl L
Follow all symbolic links.
.It Fl P
Don't follow any symbolic links.
This is the default.
.It Fl a
Include hidden files and directories when searching recursively.
.It Fl e
Excess mode. List all excess files; i.e. all but one of each cluster of duplicates.
This is useful when you want to automate removal of duplicate files.
.It Fl f Ar format
Set the format of the cluster header.
If the header is set to the empty string, no header line is printed.
.Pp
The following escape sequences are available:
.Bl -ohang -offset left
.It
.Cm %n
The number of files in the cluster.
.It
.Cm %c
The SHA1 checksum of files in the cluster.
.It
.Cm %i
The one-based index of the file cluster.
.It
.Cm %s
The size, in bytes, of a file in the cluster.
.It
.Cm %%
A
.Sq %
character.
.El
.Pp
The default format string is:
.Pp
.Dl %n files in cluster %i (%s bytes, checksum %c)
.It Fl h
Display help information and exit.
.It Fl l Ar limit
The minimum size of files to be sampled.
If the size of files in a cluster is equal or greater than the specified limit,
.Nm
will sample a few bytes from each file, before calculating a full checksum.
This is an optimization for larger files.
The default limit is 1048576 bytes.
.It Fl q
Quiet mode.
Supress warnings and error messages.
.It Fl r
Recursively search into all specified directories.
.It Fl t
Thorough mode.
Distrust checksums as a guarantee for equality.
In thorough mode,
.Nm
compares files byte by byte when their checksums match.
.It Fl v
Display version information and exit.
.It Fl z
Do not report a cluster of files with zero size.
.El
.Sh EXAMPLES
The command:
.Dl duff -e * | xargs rm
.Pp
removes all duplicate files in the current directory.
.Pp
The command:
.Dl duff -r foo/
.Pp
lists all duplicate files in the directory foo and its subdirectories.
.Sh DIAGNOSTICS
.Ex -std
.Sh AUTHORS
.An "Camilla Berglund" Aq elmindreda@users.sourceforge.net
.Sh BUGS
.Bl -bullet
.It
.Nm
does not currently detect symlink loops when using
.Fl L
(follow links). This may do bad things to your system.
.It
.Nm
does not currently intelligently handle symlinks when using
.Fl e
(excess mode) with
.Fl L
(follow links). This may do very bad things to your data.
.El
