.\" Copyright (C) Camilla Berglund
.\"
.Dd October 18, 2005
.Os
.Dt DUFF 1
.Sh NAME
.Nm duff
.Nd duplicate file finder
.Sh SYNOPSIS
.Nm
.Op Fl LPaeqrt
.Op Fl f Ar format
.Ar
.Nm
.Op Fl h
.Nm
.Op Fl v
.Sh DESCRIPTION
The
.Nm
utility reports any clusters of duplicates in the specified files.
.Pp
The following options are available:
.Bl -tag -offset indent
.It Fl L
Follow all symbolic links.
.It Fl P
Don't follow any symbolic links.
This is the default.
.It Fl a
Include hidden files and directories when searching recursively.
.It Fl e
Excess mode. List all excess files; i.e. all but one of each cluster of duplicates.
This is useful when you want to automate removal of duplicate files.
.It Fl f Ar format
Set the format string for duplicate cluster headers.
This header, unless the format string is empty, is printed once before each cluster of duplicate files.
The following escape sequences are available:
.Bl -ohang -offset left
.It
.Cm %n
The number of files in the cluster.
.It
.Cm %c
The SHA1 checksum of files in the cluster.
.It
.Cm %i
The index of the file cluster.
.It
.Cm %s
The size, in bytes, of a file in the cluster.
.It
.Cm %%
A
.Sq %
character.
.El
.Pp
The default format string is:
.Pp
.Dl %n files in cluster %i (%s bytes, checksum %c)
.It Fl h
Display help information and exit.
.It Fl q
Quiet mode; supress warnings and error messages.
.It Fl r
Recursively search into all specified directories.
.It Fl t
Thorough mode.
Distrust checksums as a guarantee for equality.
In thorough mode,
.Nm
compares files byte by byte when their checksums match.
.It Fl v
Display version information and exit.
.El
.Sh EXAMPLES
The command:
.Dl duff -e * | xargs rm
.Pp
removes all duplicate files in the current directory.
.Pp
The command:
.Dl duff -r foo/
.Pp
lists all duplicate files in the directory foo and its subdirectories.
.Sh DIAGNOSTICS
.Ex -std
.Sh AUTHORS
.An "Camilla Berglund" Aq elmindreda@users.sourceforge.net
.Sh BUGS
.Bl -bullet
.It
.Nm
does not properly detect symlink loops. Beware of runaway
.Nm
session that do bad things to your system.
.It
.Nm
Does not currently check for symlinks when using
.Fl e
This may do bad things to your data.
.El
